<?php

use Autopilot\AP3Connector\Api\Data\TrackingDataInterface as TD;
use Autopilot\AP3Connector\Block\Checkout;
use Autopilot\AP3Connector\Block\CheckoutSuccess;
use Autopilot\AP3Connector\Helper\Config;

/**
 * @var $block CheckoutSuccess
 */
$event = $block->getOrderEvent();
?>
<?php if (!empty($event)) { ?>
    <div class="display:none;" data-mage-init='{"checkout_success":  {
          "email": "<?= $event[TD::EMAIL] ?>",
          "phone": "<?= $event[TD::PHONE] ?>",
          "payload": <?= $event[TD::PAYLOAD] ?>
      }
    }'>
    </div>
<?php } ?>
