<?php

use Ortto\Connector\Block\Checkout;
use Ortto\Connector\Helper\Config;

/**
 * @var $block Checkout
 */
?>
<?php if ($event = $block->getCardEventJSON(Config::EVENT_TYPE_CHECKOUT_STARTED)) { ?>
    <div class="display:none;" id="ortto-checkout">
    </div>
    <script type="text/x-magento-init">
    {
        "#ortto-checkout": {
            "Ortto_Connector/js/checkout": <?= $event; ?>
        }
    }



    </script>
<?php } ?>
