<?php

use Ortto\Connector\Block\CheckoutSuccess;
use Ortto\Connector\Helper\Config;

/**
 * @var $block CheckoutSuccess
 */
?>

<?php if ($event = $block->getOrderEventJSON(Config::EVENT_TYPE_ORDER_CREATED)) { ?>
    <div class="display:none;" id="ortto-checkout-success">
    </div>
    <script type="text/x-magento-init">
        {
            "#ortto-checkout-success": {
                "Ortto_Connector/js/checkout_success": <?= $event; ?>
            }
        }


    </script>
<?php } ?>
