<?php
/**
 * @var $block Ortto\Connector\Block\HeaderJs
 */

use Ortto\Connector\Block\HeaderJs;

$config = $block->getConfiguration();
?>
<script type="text/javascript" id="ortto-cap"></script>
<script type="text/javascript" id="ortto-mg"></script>
<?php if (!empty($config)) { ?>
    <script type="text/javascript">
        /**
         * Initializer
         * @param {Function} ap3c.initMagento
         * @param {Object} window
         */
        window.ortto = {
            'base_url': '<?= $config[HeaderJs::BASE_URL] ?>'
        };

        window.ap3c = window.ap3c || {};
        var ap3c = window.ap3c;
        ap3c.cmd = ap3c.cmd || [];
        ap3c.cmdMagento = ap3c.cmdMagento || [];
        var options = {
            context: {
                scope: {},
                email: '<?= $config[HeaderJs::EMAIL] ?>',
                phone: ''
            },
            needsConsentToTrack: <?= $config[HeaderJs::CONSENT_TO_TRACK_REQUIRED] ?>
        };
        ap3c.cmdMagento.push(function () {
            ap3c.initMagento('<?= $config[HeaderJs::TRACKING_CODE] ?>', '<?= $config[HeaderJs::CAPTURE_API] ?>', options);
        });

        var t = document.getElementById('ortto-cap');
        t.setAttribute('src', '<?= $config[HeaderJs::CAPTURE_JS] ?>');
        t.addEventListener('load', function () {
            var mg = document.getElementById('ortto-mg');
            mg.setAttribute('src', '<?= $config[HeaderJs::MAGENTO_JS] ?>');
        });
    </script>
<?php } ?>
