<?php
/**
 * @var $block Ortto\Connector\Block\HeaderJs
 */

$config = $block->getConfiguration();
?>
<?php if (!empty($config)) { ?>
    <script type="text/javascript">
        /**
         * Initializer
         * @param {Function} ap3c.initMagento
         * @param {Object} window
         */
        window.ortto = {
            'base_url': '<?= $config->getScope()->getBaseURL() ?>'
        };

        window.ap3c = window.ap3c || {};
        var ap3c = window.ap3c;
        ap3c.cmd = ap3c.cmd || [];
        ap3c.cmdMagento = ap3c.cmdMagento || [];
        var options = {
            context: {
                scope: {},
                email: '<?= $config->getEmail() ?>',
                phone: '<?= $config->getPhone() ?>'
            },
            needsConsentToTrack: <?= $config->getNeedsConsent() ? 'true' : 'false' ?>
        };
        ap3c.cmdMagento.push(function () {
            ap3c.initMagento('<?= $config->getTrackingCode() ?>', '<?= $config->getCaptureAPI() ?>', options);
        });
    </script>
    <script type="text/javascript" src='<?= $config->getCaptureJS() ?>'></script>
    <script type="text/javascript" src='<?= $config->getMagentoJS() ?>'></script>
<?php } ?>
