<?php
/**
 * @var $block Ortto\Connector\Block\HeaderJs
 */

use Ortto\Connector\Block\HeaderJs;

$config = $block->getConfiguration();
?>

<?php if (!empty($config)) { ?>
    <script type="text/javascript">
        /**
         * Initializer
         * @param {Function} ap3c.initMagento
         * @param {Object} window
         */
        window.ortto = {
            'base_url': '<?= $config[HeaderJs::BASE_URL] ?>'
        };

        window.ap3c = window.ap3c || {};
        var ap3c = window.ap3c;
        ap3c.cmd = ap3c.cmd || [];
        ap3c.cmdMagento = ap3c.cmdMagento || [];

        var context = {
            scope: {},
            email: '',
            phone: ''
        };

        ap3c.cmdMagento.push(function () {
            ap3c.initMagento('<?= $config[HeaderJs::TRACKING_CODE] ?>', '<?= $config[HeaderJs::CAPTURE_API] ?>', context);
        });

        var s, t;
        s = document.createElement('script');
        s.type = 'text/javascript';
        s.src = '<?= $config[HeaderJs::CAPTURE_JS] ?>';
        t = document.getElementsByTagName('script')[0];
        t.parentNode.insertBefore(s, t);
        s.addEventListener('load', function () {
            var bs, bt;
            bs = document.createElement('script');
            bs.type = 'text/javascript';
            bs.src = '<?= $config[HeaderJs::MAGENTO_JS] ?>';
            bt = document.getElementsByTagName('script')[0];
            bt.parentNode.insertBefore(bs, bt);
        });
    </script>
<?php } ?>
