<?php

use Autopilot\AP3Connector\Api\Data\TrackingDataInterface as TD;
use Autopilot\AP3Connector\Block\ProductView;
use Autopilot\AP3Connector\Helper\Config;

/**
 * @var $block ProductView
 */
$event = $block->getProductEvent(Config::EVENT_TYPE_PRODUCT_VIEWED);
?>

<?php if (!empty($event)) { ?>
    <div class="display:none;" data-mage-init='{"product_view":  {
          "email": "<?= $event[TD::EMAIL] ?>",
          "phone": "<?= $event[TD::PHONE] ?>",
          "payload": <?= $event[TD::PAYLOAD] ?>
      }
    }'>
    </div>

<?php } ?>
