<?php

use Ortto\Connector\Block\ProductView;
use Ortto\Connector\Helper\Config;

/**
 * @var $block ProductView
 */
?>

<?php if ($event = $block->getEventJSON(Config::EVENT_TYPE_PRODUCT_VIEWED)) { ?>
    <div class="display:none;" id="ortto-product-view">
    </div>
    <script type="text/x-magento-init">
    {
        "#ortto-product-view": {
            "Ortto_Connector/js/product_view": <?= $event; ?>
        }
    }

    </script>
<?php } ?>


