<?php

use Autopilot\AP3Connector\Api\Data\TrackingDataInterface;
use Autopilot\AP3Connector\Helper\Config;

/**
 * @var $block Autopilot\AP3Connector\Block\Catalog\Product\View
 */
$event = $block->getProductEvent(Config::EVENT_TYPE_ADDED_VIEWED);
?>

<?php if (!empty($event)) { ?>
    <div class="display:none;" data-mage-init='{"product_view":  {
          "email": "<?= $event[TrackingDataInterface::EMAIL] ?>",
          "phone": "<?= $event[TrackingDataInterface::PHONE] ?>",
          "payload": <?= $event[TrackingDataInterface::PAYLOAD] ?>
      }
    }'>
    </div>

<?php } ?>
