---

steps:
  - block: ":rocket: Deploy to https://magento-stg.ortto.dev"

  - label: ":php: :package: Package and Deploy :k8s: :mage:"
    command: .buildkite/deploy.sh
    agents:
      env: stg
      region: ap-southeast-2
