<?php

use Autopilot\AP3Connector\Block\Adminhtml\System\Config\AuthWizard;

/**
 * @var $block AuthWizard
 */
$scope = $block->getScope();
?>

<div>
    <button
        data-mage-init='{"postData": {
                "url":"<?= $block->getAjaxURL() ?>",
                "title": "Authentication",
                "data": {
                    "client_id": "<?= $block->getEscapedAttrClientID() ?>",
                    "scope_id": <?= $scope->getId() ?>,
                    "scope_code": "<?= $scope->getCode() ?>",
                    "scope_type": "<?= $scope->getType() ?>",
                    "scope_name": "<?= $scope->getName() ?>",
                    "scope_url": "<?= $scope->getBaseURL() ?>"
                }
            }
        }' id="authenticate">
        <span><?= $block->getButtonLabel() ?>
        </span>
    </button>
</div>
