<?php

use Autopilot\AP3Connector\Block\frontend\Catalog\SyncCustomers;

/**
 * @var $block SyncCustomers
 */
?>
<div>
    <button
        data-mage-init='{"Autopilot_AP3Connector/js/post_data":
            {
                "url":"<?= /* @noEscape */
        $block->getAjaxURL() ?>",
                "scope_type": "<?= /* @noEscape */
        $block->getEscapedAttrScopeType() ?>",
                "scope_id": "<?= /* @noEscape */
        $block->getEscapedAttrScopeID() ?>",
                "client_id": "<?= /* @noEscape */
        $block->getEscapedAttrClientID() ?>"
            }
        }'
        id="sync-customers">
        <span><?= /* @noEscape */
            $block->getButtonLabel() ?>
        </span>
    </button>
</div>
