<?php

use Autopilot\AP3Connector\Block\Adminhtml\System\Config\SyncCustomers;

/**
 * @var $block SyncCustomers
 */


?>
<script type="text/javascript">
    require([
            'jquery',
            'Magento_Ui/js/modal/alert'
        ],
        function ($, alert) {
            $('#sync-customers').click(function (event) {
                event.preventDefault();
                const url = $(this).data('url');
                const body = {
                    'form_key': window.FORM_KEY,
                    "scope_type": $(this).data('scope-type'),
                    "scope_id": $(this).data('scope-id'),
                    "client_id": $(this).data('client-id')
                }
                $.ajax({
                    url: url,
                    type: "POST",
                    contentType: 'application/x-www-form-urlencoded',
                    data: body,
                    success: function (data) {
                        let title = 'Info';
                        if (data.error) {
                            title = 'Error';
                        }
                        alert({title: title, content: data.message});
                    },
                    error: function (jqXHR) {
                        if (jqXHR !== null && jqXHR !== undefined && (jqXHR.status === 400 || jqXHR.status === 401)) {
                            let message = 'Invalid Request';
                            if (jqXHR.responseJSON !== null && jqXHR.responseJSON !== undefined &&
                                jqXHR.responseJSON.message !== null && jqXHR.responseJSON.message !== undefined) {
                                message = jqXHR.responseJSON.message;
                            }
                            alert({title: "Error", content: message});
                        } else {
                            alert({title: "Error", content: "Internal Server Error"});
                        }
                    }
                });
            });
        });
</script>
<div>

    <div id="validation_result" class="message-validation"></div>
    <button
        data-url="<?= /* @noEscape */
        $block->getAjaxURL() ?>"
        data-scope-type="<?= /* @noEscape */
        $block->getEscapedAttrScopeType() ?>"
        data-scope-id="<?= /* @noEscape */
        $block->getEscapedAttrScopeID() ?>"
        data-client-id="<?= /* @noEscape */
        $block->getEscapedAttrClientID() ?>" id="sync-customers">
        <span><?= /* @noEscape */
            $block->getButtonLabel() ?></span>
    </button>
</div>
