<?php

use Ortto\Connector\Block\Adminhtml\System\Config\SyncOrders;

/**
 * @var $block SyncOrders
 */
$scope = $block->getScope();
?>
<div>
    <button
        data-mage-init='{"postData":
            {
                "url":"<?= $block->getAjaxURL() ?>",
                "title": "Orders",
                "data": {
                    "scope_id": <?= $scope->getId() ?>,
                    "scope_type": "<?= $scope->getType() ?>"
                }
            }
        }'
        id="sync-orders">
        <span><?= /* @noEscape */
            $block->getButtonLabel() ?>
        </span>
    </button>
</div>
